#!/bin/bash

apiuser=APIUSER
apipasswd=APIPASSWORD

# created base64-encoded credentials
encodedCredentials=$( printf "$apiuser:$apipasswd" | /usr/bin/iconv -t ISO-8859-1 | /usr/bin/base64 -i - )

echo $encodedCredentials
