#!/bin/bash
#
# Created by Perry Driscoll 31/1/2022
#
# LAPS FOR JAMF
#
# Script to Decrypt LAPS password
#
# JAMF Script Variables
# $4: API Username
# $5: API Password
# $6: JSS URL
#
####################################################

# Pop up for Device name

user=$4
passwd=$5

name=$(osascript -e 'Tell application "System Events" to display dialog "Enter the name of the device you want the LAPS password for." with title "LAPS Password" with icon alias "System:Applications:Utilities:Keychain Access.app:Contents:Resources:AppIcon.icns" default answer ""' -e 'text returned of result' 2>/dev/null)

cryptpass=$(curl -k -s -u $user:$passwd -X "GET" "https://$6/JSSResource/computers/name/$name/subset/extension_attributes" -H "Accept: application/json" | tr '{' '\n' | grep LAPS | tr '"' ' ' | awk '{print $16}')
	
# Pop up for decryption secret
secretkey=$(osascript -e 'Tell application "System Events" to display dialog "Enter the decryption password in the box below" with title "LAPS Password" with icon alias "System:Applications:Utilities:Keychain Access.app:Contents:Resources:AppIcon.icns" with hidden answer default answer ""' -e 'text returned of result' 2>/dev/null)

# Decrypt password and display

passwd=$(echo $cryptpass | openssl enc -aes-256-cbc -md sha512 -a -d -salt -pass pass:$secretkey)

osascript -e 'Tell application "System Events" to display dialog "Local admin password is: 
'"$passwd"'

This message will disappear after 10seconds" with title "LAPS Password" with icon alias "System:Applications:Utilities:Keychain Access.app:Contents:Resources:AppIcon.icns" giving up after (10)' 2>/dev/null
