#!/bin/bash
#
# Created by Perry Driscoll 31/1/2022
#
# LAPS FOR JAMF
#
# Script to Decrypt LAPS password
#
# JAMF Script Variables
# $4: JSS URL
# $5: Encrypted API Credentials
#
####################################################

# API Credentials
encryptedcreds="$5"

token=$(curl -s -H "Content-Type: application/json" -H "Authorization: Basic ${encryptedcreds}" -X POST "$4/api/v1/auth/token" | grep 'token' | tr -d '"',',' | sed -e 's#token :##' | xargs)

# Pop up for Device name

name=$(osascript -e 'Tell application "System Events" to display dialog "Enter the name of the device you want the LAPS password for." with title "LAPS Password" with icon alias "System:Applications:Utilities:Keychain Access.app:Contents:Resources:AppIcon.icns" default answer ""' -e 'text returned of result' 2>/dev/null)

# Grab decryption key for password
cryptkey=$(curl -s -X "GET" "$4/JSSResource/computers/name/$name/subset/extension_attributes" -H "Accept: application/json" -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep -i CryptKey | tr '"' ' ' | awk '{print $16}')


# Grab secret for decryption
secretkey=$(curl -s -X "GET" "$4/JSSResource/computers/name/$name/subset/extension_attributes" -H "Accept: application/json" -H "Authorization:Bearer ${token}" | tr '{' '\n' | grep -i Secret | tr '"' ' ' | awk '{print $16}')

# Decrypt password and display

passwd=$(echo $cryptkey | openssl enc -aes-256-cbc -md sha512 -a -d -salt -pass pass:$secretkey)

osascript -e 'Tell application "System Events" to display dialog "Local admin password is: 
'"$passwd"'

This message will disappear after 10seconds" with title "LAPS Password" with icon alias "System:Applications:Utilities:Keychain Access.app:Contents:Resources:AppIcon.icns" giving up after (10)' 2>/dev/null
